FROM node

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

RUN npm install

# Bundle app source
COPY . .

# Use other port if not using https
EXPOSE 5173

# ATTENTION!!! DANGER!!! THIS WILL RESET XREATE DATABASE. Use it only if you know what you are doing.
CMD [ "npm", "run", "start" ]


# This is the normal use Entry point. Comment this line for the installation, and afterwards uncomment it forever.
# ENTRYPOINT [ "npm", "run", "db:migrate-and-start" ]